/**
 * useVersionCheck — detects when a new frontend deploy is available and reloads.
 *
 * How it works:
 *  1. On mount, fetches /version.json with cache:no-store (always hits the CDN origin).
 *  2. Compares the fetched version against NEXT_PUBLIC_APP_VERSION embedded at build time.
 *  3. If they differ → the user is running a stale build → hard reload.
 *  4. Repeats every `intervalMs` (default 5 min) while the tab is open.
 *
 * Why /version.json instead of re-fetching the page itself?
 *  - Tiny payload (~20 bytes), no parse cost.
 *  - Azure SWA CDN respects Cache-Control on static files.
 *  - The file is regenerated by the CI workflow on every deploy.
 */

import { useEffect } from "react";

const CURRENT_VERSION = process.env.NEXT_PUBLIC_APP_VERSION ?? "dev";

async function fetchDeployedVersion(): Promise<string | null> {
  try {
    const res = await fetch("/version.json", { cache: "no-store" });
    if (!res.ok) return null;
    const data = (await res.json()) as { version?: string };
    return data.version ?? null;
  } catch {
    return null;
  }
}

export function useVersionCheck(intervalMs = 5 * 60 * 1000): void {
  useEffect(() => {
    // Skip in local dev — version is always "dev" so no reload loop.
    if (CURRENT_VERSION === "dev") return;

    let cancelled = false;

    async function check() {
      const deployed = await fetchDeployedVersion();
      if (!cancelled && deployed && deployed !== CURRENT_VERSION) {
        window.location.reload();
      }
    }

    // Check immediately on mount, then on interval.
    check();
    const id = setInterval(check, intervalMs);

    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [intervalMs]);
}
